// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABDr1Su9rdbeZPv4QzoXcVe6ugbSwnNhE',
    appId: '1:737432795698:web:1fda4c3829967d3ea7da2b',
    messagingSenderId: '737432795698',
    projectId: 'utahpainting-17',
    authDomain: 'utahpainting-17.firebaseapp.com',
    storageBucket: 'utahpainting-17.firebasestorage.app',
    measurementId: 'G-M1957WKPGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOJWi1xvGU9VDn3qQJixzr0uEp0v5toYs',
    appId: '1:737432795698:android:029af9e0e8ff1751a7da2b',
    messagingSenderId: '737432795698',
    projectId: 'utahpainting-17',
    storageBucket: 'utahpainting-17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdCGNoHaOisFCg-SH2Nezu6VPo8JMzOjA',
    appId: '1:737432795698:ios:7d29c1d6d02c1a2ea7da2b',
    messagingSenderId: '737432795698',
    projectId: 'utahpainting-17',
    storageBucket: 'utahpainting-17.firebasestorage.app',
    iosBundleId: 'com.utah.paintingapp.utah_painting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdCGNoHaOisFCg-SH2Nezu6VPo8JMzOjA',
    appId: '1:737432795698:ios:7d29c1d6d02c1a2ea7da2b',
    messagingSenderId: '737432795698',
    projectId: 'utahpainting-17',
    storageBucket: 'utahpainting-17.firebasestorage.app',
    iosBundleId: 'com.utah.paintingapp.utah_painting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABDr1Su9rdbeZPv4QzoXcVe6ugbSwnNhE',
    appId: '1:737432795698:web:245d9ed0b63adee6a7da2b',
    messagingSenderId: '737432795698',
    projectId: 'utahpainting-17',
    authDomain: 'utahpainting-17.firebaseapp.com',
    storageBucket: 'utahpainting-17.firebasestorage.app',
    measurementId: 'G-D2TWGC6FXP',
  );

}